#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# nvim
ln -s ${BASEDIR}/nvim $HOME/.config/nvim

# wezterm terminal
rm $HOME/.wezterm.lua
ln -sf ${BASEDIR}/wezterm/wezterm.lua $HOME/.wezterm.lua
